version: "3.9"
services:
    postgres:
        image: postgres:13
        restart: always
        environment:
            POSTGRES_DB: mydb
            POSTGRES_USER: my_user
            POSTGRES_PASSWORD: my_password
        ports:
            - '5432:5432'
        networks:
            - my_network

networks:
    my_network: