version: "3.9"
services:
    backend:
        build: 
            context: ./backend
        restart: on-failure:3
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgresql://my_user:my_password@postgres:5432/my_db
        networks:
            - my_network

    postgres:
        image: postgres:13
        restart: always
        environment:
            POSTGRES_DB: my_db
            POSTGRES_USER: my_user
            POSTGRES_PASSWORD: my_password
        ports:
            - '5432:5432'
        networks:
            - my_network
    # nginx:
    #     image: nginx
    #     ports:
    #         - "80:80"
    #     volumes:
    #         - ./nginx.conf:/etc/nginx/conf.d/default.conf
    #     depends_on:
    #         - web
networks:
    my_network: