version: "3.9"
services:
    frontend:
        build:
            context: ./frontend  
        restart: on-failure:3
        depends_on:
            - backend
        networks:
            - my_network

    backend:
        build: 
            context: ./backend
        restart: on-failure:3
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgresql://my_user:my_password@postgres:5432/my_db
            CORS_ORIGINS: http://localhost:3000,https://localhost:8443,http://localhost:8443
        networks:
            - my_network

    postgres:
        image: postgres:13
        restart: always
        environment:
            POSTGRES_DB: my_db
            POSTGRES_USER: my_user
            POSTGRES_PASSWORD: my_password
        networks:
            - my_network
    
    nginx:
        image: nginx
        ports:
            - "8443:8443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/certificates:/etc/nginx/certificates
        restart: always
        depends_on:
            - frontend
            - backend
        networks:
            - my_network
            
networks:
    my_network: